package generator

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/shunshouda/mapstruct/parser"
)

// TypePair 类型对
type TypePair struct {
	SourcePkg  string
	SourceType string
	DestPkg    string
	DestType   string
}

// FieldMapping 字段映射
type FieldMapping struct {
	SourceField parser.FieldInfo
	DestField   parser.FieldInfo
	MappingType string // "name", "json", "tag"
}

// StructMapping 结构体映射
type StructMapping struct {
	Source      *parser.StructInfo
	Dest        *parser.StructInfo
	FieldMaps   []FieldMapping
	MethodName  string
	NeedImports map[string]string // 包名 -> 导入路径
}

// Generator 代码生成器
type Generator struct {
	PackageName       string
	StructMappings    []StructMapping
	UsedPackages      map[string]string             // 包名 -> 导入路径
	allStructs        map[string]*parser.StructInfo // 所有结构体信息，用于递归生成
	generatedMappings map[string]bool               // 记录已生成的映射，避免重复
}

// NewGenerator 创建新的生成器
func NewGenerator(packageName string) *Generator {
	return &Generator{
		PackageName:       packageName,
		StructMappings:    make([]StructMapping, 0),
		UsedPackages:      make(map[string]string),
		allStructs:        make(map[string]*parser.StructInfo),
		generatedMappings: make(map[string]bool),
	}
}

// SetAllStructs 设置所有结构体信息，用于递归生成嵌套映射
func (g *Generator) SetAllStructs(allStructs map[string]*parser.StructInfo) {
	g.allStructs = allStructs
}

// AddMapping 添加结构体映射
func (g *Generator) AddMapping(source, dest *parser.StructInfo) {
	mapping := StructMapping{
		Source:      source,
		Dest:        dest,
		FieldMaps:   g.buildFieldMappings(source, dest),
		MethodName:  fmt.Sprintf("%sTo%s", source.Name, dest.Name),
		NeedImports: make(map[string]string),
	}

	// 记录需要导入的包 - 使用完整的导入路径
	if source.Package != g.PackageName && source.ImportPath != "" {
		importAlias := g.getImportAlias(source.Package, source.ImportPath)
		mapping.NeedImports[importAlias] = source.ImportPath
		g.UsedPackages[importAlias] = source.ImportPath
	}

	if dest.Package != g.PackageName && dest.ImportPath != "" {
		importAlias := g.getImportAlias(dest.Package, dest.ImportPath)
		mapping.NeedImports[importAlias] = dest.ImportPath
		g.UsedPackages[importAlias] = dest.ImportPath
	}

	g.StructMappings = append(g.StructMappings, mapping)

	// 标记此映射为已生成
	mappingKey := fmt.Sprintf("%s.%s->%s.%s",
		source.Package, source.Name,
		dest.Package, dest.Name)
	g.generatedMappings[mappingKey] = true
}

// getImportAlias 获取导入别名
func (g *Generator) getImportAlias(pkgName, importPath string) string {
	// 如果包名在导入路径的最后一部分，使用包名作为别名
	base := filepath.Base(importPath)
	if base == pkgName {
		return pkgName
	}

	// 检查是否已有冲突的导入
	for alias, path := range g.UsedPackages {
		if alias == pkgName && path != importPath {
			// 有冲突，使用导入路径的最后两部分作为别名
			parts := strings.Split(importPath, "/")
			if len(parts) >= 2 {
				return parts[len(parts)-2] + "_" + parts[len(parts)-1]
			}
			return pkgName + "_ext"
		}
	}

	// 否则，使用包名作为别名（避免冲突时可能需要处理）
	return pkgName
}

// buildFieldMappings 构建字段映射关系
func (g *Generator) buildFieldMappings(source, dest *parser.StructInfo) []FieldMapping {
	var mappings []FieldMapping

	// 1. 首先处理显式标签映射
	for _, sourceField := range source.Fields {
		if destField := dest.GetMapStructField(sourceField.Name); destField != nil {
			mappings = append(mappings, FieldMapping{
				SourceField: sourceField,
				DestField:   *destField,
				MappingType: "tag",
			})
		}
	}

	// 2. 处理 JSON 名称映射
	for _, sourceField := range source.Fields {
		if sourceField.JSONName == "" {
			continue
		}

		// 跳过已映射的字段
		alreadyMapped := false
		for _, mapping := range mappings {
			if mapping.SourceField.Name == sourceField.Name {
				alreadyMapped = true
				break
			}
		}
		if alreadyMapped {
			continue
		}

		if destField := dest.GetFieldByJSONName(sourceField.JSONName); destField != nil {
			mappings = append(mappings, FieldMapping{
				SourceField: sourceField,
				DestField:   *destField,
				MappingType: "json",
			})
		}
	}

	// 3. 然后处理同名字段
	for _, sourceField := range source.Fields {
		// 跳过已映射的字段
		alreadyMapped := false
		for _, mapping := range mappings {
			if mapping.SourceField.Name == sourceField.Name {
				alreadyMapped = true
				break
			}
		}
		if alreadyMapped {
			continue
		}

		if destField := dest.GetFieldByName(sourceField.Name); destField != nil {
			mappings = append(mappings, FieldMapping{
				SourceField: sourceField,
				DestField:   *destField,
				MappingType: "name",
			})
		}
	}

	return mappings
}

// Generate 生成代码
func (g *Generator) Generate() (string, error) {
	var builder strings.Builder

	// 文件头
	builder.WriteString("// Code generated by mapstruct. DO NOT EDIT.\n")
	builder.WriteString("// versions:\n")
	builder.WriteString("//   mapstruct v1.0.0\n\n")

	// 包声明
	if g.PackageName != "" {
		builder.WriteString(fmt.Sprintf("package %s\n\n", g.PackageName))
	} else if len(g.StructMappings) > 0 {
		builder.WriteString(fmt.Sprintf("package %s\n\n", g.StructMappings[0].Source.Package))
	} else {
		builder.WriteString("package main\n\n")
	}

	// 导入语句
	if len(g.UsedPackages) > 0 {
		builder.WriteString("import (\n")
		for alias, importPath := range g.UsedPackages {
			if alias != "" && importPath != "" {
				// 只有当别名和导入路径的最后一个部分不同时才使用别名
				basePkg := filepath.Base(importPath)
				if alias == basePkg {
					builder.WriteString(fmt.Sprintf("\t\"%s\"\n", importPath))
				} else {
					builder.WriteString(fmt.Sprintf("\t%s \"%s\"\n", alias, importPath))
				}
			}
		}
		builder.WriteString(")\n\n")
	}

	// 首先生成所有主映射函数（不生成嵌套映射的代码）
	for _, mapping := range g.StructMappings {
		builder.WriteString(g.generateMappingFunction(mapping))
		builder.WriteString("\n\n")
	}

	// 然后生成所有需要的嵌套对象映射函数
	g.generateNestedMappings(&builder)

	return builder.String(), nil
}

// generateNestedMappings 生成所有嵌套对象的映射函数
func (g *Generator) generateNestedMappings(builder *strings.Builder) {
	// 收集所有需要生成的嵌套映射
	toGenerate := make([]struct {
		source *parser.StructInfo
		dest   *parser.StructInfo
	}, 0)

	// 遍历所有已注册的映射，查找嵌套对象
	for _, mapping := range g.StructMappings {
		g.collectNestedMappings(mapping.Source, mapping.Dest, &toGenerate)
	}

	// 生成收集到的嵌套映射
	for _, pair := range toGenerate {
		mappingKey := fmt.Sprintf("%s.%s->%s.%s",
			pair.source.Package, pair.source.Name,
			pair.dest.Package, pair.dest.Name)

		// 如果已经生成过，跳过
		if g.generatedMappings[mappingKey] {
			continue
		}

		// 创建新的映射
		newMapping := StructMapping{
			Source:      pair.source,
			Dest:        pair.dest,
			FieldMaps:   g.buildFieldMappings(pair.source, pair.dest),
			MethodName:  fmt.Sprintf("%sTo%s", pair.source.Name, pair.dest.Name),
			NeedImports: make(map[string]string),
		}

		// 记录需要导入的包
		if pair.source.Package != g.PackageName && pair.source.ImportPath != "" {
			importAlias := g.getImportAlias(pair.source.Package, pair.source.ImportPath)
			newMapping.NeedImports[importAlias] = pair.source.ImportPath
			g.UsedPackages[importAlias] = pair.source.ImportPath
		}

		if pair.dest.Package != g.PackageName && pair.dest.ImportPath != "" {
			importAlias := g.getImportAlias(pair.dest.Package, pair.dest.ImportPath)
			newMapping.NeedImports[importAlias] = pair.dest.ImportPath
			g.UsedPackages[importAlias] = pair.dest.ImportPath
		}

		// 生成映射函数
		builder.WriteString(g.generateMappingFunction(newMapping))
		builder.WriteString("\n\n")

		// 标记为已生成
		g.generatedMappings[mappingKey] = true

		// 递归处理这个嵌套映射的子嵌套对象
		g.collectNestedMappings(pair.source, pair.dest, &toGenerate)
	}
}

// collectNestedMappings 收集嵌套对象的映射对
func (g *Generator) collectNestedMappings(source, dest *parser.StructInfo, toGenerate *[]struct {
	source *parser.StructInfo
	dest   *parser.StructInfo
}) {
	// 使用 map 来避免重复检查，O(1) 复杂度
	existingMap := make(map[string]bool, len(*toGenerate))
	for _, pair := range *toGenerate {
		key := fmt.Sprintf("%s.%s->%s.%s",
			pair.source.Package, pair.source.Name,
			pair.dest.Package, pair.dest.Name)
		existingMap[key] = true
	}

	// 遍历源结构体的所有字段
	for _, sourceField := range source.Fields {
		// 如果不是嵌套对象，跳过
		if !sourceField.IsNestedObject || sourceField.NestedStructInfo == nil {
			continue
		}

		// 在目标结构体中查找对应的字段
		destField := dest.GetFieldByName(sourceField.Name)
		if destField == nil {
			// 尝试通过 JSON 标签查找
			if sourceField.JSONName != "" {
				destField = dest.GetFieldByJSONName(sourceField.JSONName)
			}
		}

		if destField == nil || !destField.IsNestedObject || destField.NestedStructInfo == nil {
			continue
		}

		// 找到一对嵌套对象
		nestedSource := sourceField.NestedStructInfo
		nestedDest := destField.NestedStructInfo

		if nestedSource != nil && nestedDest != nil {
			mappingKey := fmt.Sprintf("%s.%s->%s.%s",
				nestedSource.Package, nestedSource.Name,
				nestedDest.Package, nestedDest.Name)

			if existingMap[mappingKey] || g.generatedMappings[mappingKey] {
				continue
			}

			*toGenerate = append(*toGenerate, struct {
				source *parser.StructInfo
				dest   *parser.StructInfo
			}{
				source: nestedSource,
				dest:   nestedDest,
			})
			existingMap[mappingKey] = true
		}
	}
}

// generateMappingFunction 生成单个映射函数
func (g *Generator) generateMappingFunction(mapping StructMapping) string {
	var builder strings.Builder

	// 函数注释
	builder.WriteString(fmt.Sprintf("// %s 将 %s.%s 映射到 %s.%s\n",
		mapping.MethodName, mapping.Source.Package, mapping.Source.Name,
		mapping.Dest.Package, mapping.Dest.Name))

	// 函数签名
	sourceType := g.getQualifiedType(mapping.Source)
	destType := g.getQualifiedType(mapping.Dest)

	builder.WriteString(fmt.Sprintf("func %s(src *%s) *%s {\n",
		mapping.MethodName, sourceType, destType))

	// 空值检查
	builder.WriteString("\tif src == nil {\n")
	builder.WriteString("\t\treturn nil\n")
	builder.WriteString("\t}\n\n")

	// 创建目标对象
	builder.WriteString(fmt.Sprintf("\tdst := &%s{}\n\n", destType))

	// 字段赋值
	for _, fieldMap := range mapping.FieldMaps {
		assignment := g.generateFieldAssignment(mapping, fieldMap)
		if assignment != "" {
			builder.WriteString(fmt.Sprintf("\t%s\n", assignment))
		}
	}

	builder.WriteString("\n\treturn dst\n")
	builder.WriteString("}\n")

	return builder.String()
}

// getQualifiedType 获取限定类型名（包含包名）
func (g *Generator) getQualifiedType(structInfo *parser.StructInfo) string {
	if structInfo.Package == g.PackageName || structInfo.Package == "" {
		return structInfo.Name
	}

	// 查找导入别名
	for alias, importPath := range g.UsedPackages {
		basePkg := filepath.Base(importPath)
		if alias == structInfo.Package || basePkg == structInfo.Package {
			return alias + "." + structInfo.Name
		}
	}

	return structInfo.Package + "." + structInfo.Name
}

// generateFieldAssignment 生成字段赋值语句
func (g *Generator) generateFieldAssignment(mapping StructMapping, fieldMap FieldMapping) string {
	sourceType := fieldMap.SourceField.Type
	destType := fieldMap.DestField.Type

	// 构建源字段访问路径
	var sourceFieldPath []string
	if len(fieldMap.SourceField.EmbeddedPath) > 0 {
		sourceFieldPath = append(sourceFieldPath, fieldMap.SourceField.EmbeddedPath...)
	}
	sourceFieldPath = append(sourceFieldPath, fieldMap.SourceField.Name)
	sourceFieldRef := "src." + strings.Join(sourceFieldPath, ".")

	// 构建目标字段访问路径
	var destFieldPath []string
	if len(fieldMap.DestField.EmbeddedPath) > 0 {
		destFieldPath = append(destFieldPath, fieldMap.DestField.EmbeddedPath...)
	}
	destFieldPath = append(destFieldPath, fieldMap.DestField.Name)
	destFieldRef := "dst." + strings.Join(destFieldPath, ".")

	// 如果是嵌套对象，生成递归调用
	if fieldMap.SourceField.IsNestedObject && fieldMap.DestField.IsNestedObject {
		methodName := fmt.Sprintf("%sTo%s",
			fieldMap.SourceField.NestedStructInfo.Name,
			fieldMap.DestField.NestedStructInfo.Name)

		// 处理指针类型
		if strings.HasPrefix(sourceType, "*") && strings.HasPrefix(destType, "*") {
			return fmt.Sprintf("%s = %s(%s)", destFieldRef, methodName, sourceFieldRef)
		}

		if strings.HasPrefix(sourceType, "*") && !strings.HasPrefix(destType, "*") {
			return fmt.Sprintf("if %s != nil {\n\t\ttmp := %s(%s)\n\t\tif tmp != nil {\n\t\t\t%s = *tmp\n\t\t}\n\t}",
				sourceFieldRef, methodName, sourceFieldRef, destFieldRef)
		}

		if !strings.HasPrefix(sourceType, "*") && strings.HasPrefix(destType, "*") {
			return fmt.Sprintf("%s = %s(&%s)", destFieldRef, methodName, sourceFieldRef)
		}

		// 都是值类型
		return fmt.Sprintf("%s = %s(%s)", destFieldRef, methodName, sourceFieldRef)
	}

	// 类型完全匹配
	if sourceType == destType {
		return fmt.Sprintf("%s = %s", destFieldRef, sourceFieldRef)
	}

	// 指针类型处理
	if strings.HasPrefix(sourceType, "*") && !strings.HasPrefix(destType, "*") {
		baseType := strings.TrimPrefix(sourceType, "*")
		if baseType == destType {
			return fmt.Sprintf("if %s != nil {\n\t\t%s = *%s\n\t}",
				sourceFieldRef, destFieldRef, sourceFieldRef)
		}
	}

	if !strings.HasPrefix(sourceType, "*") && strings.HasPrefix(destType, "*") {
		baseType := strings.TrimPrefix(destType, "*")
		if sourceType == baseType {
			return fmt.Sprintf("%s = &%s", destFieldRef, sourceFieldRef)
		}
	}

	// 基本类型转换
	if g.isConvertibleType(sourceType, destType) {
		return fmt.Sprintf("%s = %s(%s)", destFieldRef, destType, sourceFieldRef)
	}

	// 时间类型转换
	if sourceType == "time.Time" && destType == "string" {
		return fmt.Sprintf("%s = %s.Format(\"2006-01-02 15:04:05\")",
			destFieldRef, sourceFieldRef)
	}

	if sourceType == "string" && destType == "time.Time" {
		return fmt.Sprintf("if t, err := time.Parse(\"2006-01-02 15:04:05\", %s); err == nil {\n\t\t%s = t\n\t}",
			sourceFieldRef, destFieldRef)
	}

	// 跨包类型转换（简化处理）
	if g.isSameTypeDifferentPackage(sourceType, destType, mapping) {
		// 如果是同一个类型但在不同的包，直接赋值
		return fmt.Sprintf("%s = %s", destFieldRef, sourceFieldRef)
	}

	// 无法自动转换，生成注释
	return fmt.Sprintf("// TODO: 手动实现字段映射 %s.%s -> %s.%s: %s -> %s",
		mapping.Source.Package, fieldMap.SourceField.Name,
		mapping.Dest.Package, fieldMap.DestField.Name,
		sourceType, destType)
}

// isConvertibleType 检查是否可转换的基本类型
func (g *Generator) isConvertibleType(sourceType, destType string) bool {
	convertiblePairs := map[string][]string{
		"int":     {"int8", "int16", "int32", "int64", "float32", "float64"},
		"int8":    {"int", "int16", "int32", "int64", "float32", "float64"},
		"int16":   {"int", "int8", "int32", "int64", "float32", "float64"},
		"int32":   {"int", "int8", "int16", "int64", "float32", "float64"},
		"int64":   {"int", "int8", "int16", "int32", "float32", "float64"},
		"float32": {"int", "int8", "int16", "int32", "int64", "float64"},
		"float64": {"int", "int8", "int16", "int32", "int64", "float32"},
		"string":  {"[]byte"},
		"[]byte":  {"string"},
	}

	allowedDests, exists := convertiblePairs[sourceType]
	if !exists {
		return false
	}

	for _, allowed := range allowedDests {
		if allowed == destType {
			return true
		}
	}
	return false
}

// isSameTypeDifferentPackage 检查是否是同类型但在不同包
func (g *Generator) isSameTypeDifferentPackage(sourceType, destType string, mapping StructMapping) bool {
	// 简化实现：检查类型名是否相同但包不同
	sourceTypeName := g.getTypeNameWithoutPackage(sourceType)
	destTypeName := g.getTypeNameWithoutPackage(destType)

	return sourceTypeName == destTypeName && sourceTypeName != ""
}

// getTypeNameWithoutPackage 获取不包含包名的类型名
func (g *Generator) getTypeNameWithoutPackage(typeName string) string {
	parts := strings.Split(typeName, ".")
	if len(parts) > 1 {
		return parts[1]
	}
	return parts[0]
}
