// Code generated by mapstruct. DO NOT EDIT.
// versions:
//   mapstruct v1.0.0

package examples

import (
	"github.com/shunshouda/mapstruct/examples/user"
	"github.com/shunshouda/mapstruct/examples/dto"
	"github.com/shunshouda/mapstruct/examples/response"
)

// UserToUserDTO 将 user.User 映射到 dto.UserDTO
func UserToUserDTO(src *user.User) *dto.UserDTO {
	if src == nil {
		return nil
	}

	dst := &dto.UserDTO{}

	dst.ID = src.ID
	dst.Name = src.Name
	dst.Age = int32(src.Age)
	dst.Status = src.Status
	dst.Tags = src.Tags
	dst.Email = src.Email
	dst.CreatedAt = src.CreatedAt.Format("2006-01-02 15:04:05")

	return dst
}


// UserToUserResponse 将 user.User 映射到 response.UserResponse
func UserToUserResponse(src *user.User) *response.UserResponse {
	if src == nil {
		return nil
	}

	dst := &response.UserResponse{}

	dst.UserDTO.ID = src.ID
	dst.UserDTO.Name = src.Name
	dst.Email = src.Email
	dst.UserDTO.Age = int32(src.Age)
	dst.UserDTO.Status = src.Status
	dst.UserDTO.Tags = src.Tags
	dst.UU = UserToUserResponse(src.UU)
	dst.UserDTO.CreatedAt = src.CreatedAt.Format("2006-01-02 15:04:05")

	return dst
}


// UserToUserResponse1 将 user.User 映射到 examples.UserResponse1
func UserToUserResponse1(src *user.User) *UserResponse1 {
	if src == nil {
		return nil
	}

	dst := &UserResponse1{}

	dst.ID = src.ID
	dst.Name = src.Name
	dst.Email = src.Email
	dst.Age = src.Age
	dst.Status = src.Status

	return dst
}


